-- =====================================================================
-- V1 - Schema central do dominio (saude e historico do pet)
--
-- A partir desta versao o Hibernate roda com ddl-auto=validate: o schema
-- e criado e evoluido exclusivamente por estes scripts, e o Hibernate
-- apenas confere se as entidades correspondem ao que existe no banco.
-- =====================================================================

CREATE TABLE tutors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(150) NOT NULL,
    phone      VARCHAR(11),
    cpf        VARCHAR(11)  NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT uk_tutors_email UNIQUE (email),
    CONSTRAINT uk_tutors_cpf   UNIQUE (cpf)
);

CREATE TABLE veterinarians (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    crmv       VARCHAR(20)  NOT NULL,
    email      VARCHAR(150),
    phone      VARCHAR(11),
    specialty  VARCHAR(100),
    created_at TIMESTAMP,
    CONSTRAINT uk_veterinarians_crmv UNIQUE (crmv)
);

CREATE TABLE pets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)  NOT NULL,
    species         VARCHAR(20)  NOT NULL,
    breed           VARCHAR(80),
    birth_date      DATE         NOT NULL,
    weight          NUMERIC(5, 2),
    gender          VARCHAR(10),
    profile_public  BOOLEAN      NOT NULL DEFAULT FALSE,
    tutor_id        BIGINT       NOT NULL,
    veterinarian_id BIGINT,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT fk_pets_tutor FOREIGN KEY (tutor_id)
        REFERENCES tutors (id) ON DELETE CASCADE,
    CONSTRAINT fk_pets_veterinarian FOREIGN KEY (veterinarian_id)
        REFERENCES veterinarians (id) ON DELETE SET NULL
);

CREATE TABLE vaccines (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100) NOT NULL,
    manufacturer       VARCHAR(100),
    application_date   DATE         NOT NULL,
    next_dose_date     DATE,
    certificate_number VARCHAR(50),
    notes              VARCHAR(500),
    pet_id             BIGINT       NOT NULL,
    veterinarian_id    BIGINT,
    created_at         TIMESTAMP,
    CONSTRAINT fk_vaccines_pet FOREIGN KEY (pet_id)
        REFERENCES pets (id) ON DELETE CASCADE,
    CONSTRAINT fk_vaccines_veterinarian FOREIGN KEY (veterinarian_id)
        REFERENCES veterinarians (id) ON DELETE SET NULL
);

CREATE TABLE clinical_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE         NOT NULL,
    description     VARCHAR(200) NOT NULL,
    diagnosis       VARCHAR(300),
    treatment       VARCHAR(500),
    weight          NUMERIC(5, 2),
    observations    VARCHAR(1000),
    pet_id          BIGINT       NOT NULL,
    veterinarian_id BIGINT,
    created_at      TIMESTAMP,
    CONSTRAINT fk_clinical_records_pet FOREIGN KEY (pet_id)
        REFERENCES pets (id) ON DELETE CASCADE,
    CONSTRAINT fk_clinical_records_veterinarian FOREIGN KEY (veterinarian_id)
        REFERENCES veterinarians (id) ON DELETE SET NULL
);

CREATE TABLE reminders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(20)  NOT NULL,
    due_date   DATE         NOT NULL,
    message    VARCHAR(300) NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    pet_id     BIGINT       NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT fk_reminders_pet FOREIGN KEY (pet_id)
        REFERENCES pets (id) ON DELETE CASCADE
);

CREATE TABLE activity_check_ins (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date             DATE        NOT NULL,
    activity_type    VARCHAR(20) NOT NULL,
    duration_minutes INTEGER,
    notes            VARCHAR(500),
    pet_id           BIGINT      NOT NULL,
    created_at       TIMESTAMP,
    CONSTRAINT fk_activity_check_ins_pet FOREIGN KEY (pet_id)
        REFERENCES pets (id) ON DELETE CASCADE,
    -- Regra "um check-in por pet por dia" garantida no banco, e nao apenas
    -- no service: protege contra requisicoes concorrentes.
    CONSTRAINT uk_check_in_pet_date UNIQUE (pet_id, date)
);

CREATE TABLE pet_streaks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id          BIGINT      NOT NULL,
    current_streak  INTEGER     NOT NULL DEFAULT 0,
    longest_streak  INTEGER     NOT NULL DEFAULT 0,
    last_check_in   DATE,
    level           VARCHAR(20) NOT NULL DEFAULT 'BEGINNER',
    total_check_ins INTEGER     NOT NULL DEFAULT 0,
    updated_at      TIMESTAMP,
    CONSTRAINT fk_pet_streaks_pet FOREIGN KEY (pet_id)
        REFERENCES pets (id) ON DELETE CASCADE,
    CONSTRAINT uk_pet_streaks_pet UNIQUE (pet_id)
);

-- O PostgreSQL nao cria indice automatico para chave estrangeira. Sem estes
-- indices, toda listagem "por pet" faria varredura sequencial na tabela.
CREATE INDEX idx_pets_tutor              ON pets (tutor_id);
CREATE INDEX idx_pets_veterinarian       ON pets (veterinarian_id);
CREATE INDEX idx_vaccines_pet            ON vaccines (pet_id);
CREATE INDEX idx_clinical_records_pet    ON clinical_records (pet_id);
CREATE INDEX idx_reminders_pet_status    ON reminders (pet_id, status);
CREATE INDEX idx_check_ins_pet_date      ON activity_check_ins (pet_id, date DESC);
