-- =====================================================================
-- V2 - Schema de autenticacao e autorizacao
--
-- A tabela users guarda apenas credenciais e perfil. Os dados de dominio
-- continuam em tutors e veterinarians: um usuario aponta para o registro
-- de dominio correspondente ao seu perfil.
-- =====================================================================

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(150) NOT NULL,
    -- Hash BCrypt: 60 caracteres, prefixo $2a$10$. Nunca a senha em texto plano.
    password        VARCHAR(100) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    tutor_id        BIGINT,
    veterinarian_id BIGINT,
    created_at      TIMESTAMP,

    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_tutor FOREIGN KEY (tutor_id)
        REFERENCES tutors (id) ON DELETE CASCADE,
    CONSTRAINT fk_users_veterinarian FOREIGN KEY (veterinarian_id)
        REFERENCES veterinarians (id) ON DELETE CASCADE,

    -- Um registro de dominio pertence a no maximo uma conta de acesso.
    CONSTRAINT uk_users_tutor        UNIQUE (tutor_id),
    CONSTRAINT uk_users_veterinarian UNIQUE (veterinarian_id),

    -- Coerencia entre perfil e vinculo de dominio: o banco recusa um TUTOR
    -- sem tutor_id ou um VETERINARIAN apontando para um tutor.
    CONSTRAINT ck_users_role_link CHECK (
        (role = 'TUTOR'        AND tutor_id IS NOT NULL AND veterinarian_id IS NULL) OR
        (role = 'VETERINARIAN' AND veterinarian_id IS NOT NULL AND tutor_id IS NULL) OR
        (role = 'ADMIN'        AND tutor_id IS NULL     AND veterinarian_id IS NULL)
    )
);

CREATE INDEX idx_users_role ON users (role);
