-- =====================================================================
-- V3 - Solicitacao de vinculo entre tutor e veterinario
--
-- Suporta o fluxo de aprovacao: o tutor solicita o vinculo de um pet a um
-- veterinario, e o veterinario responde. O estado vive nesta tabela, nao
-- no campo pets.veterinarian_id -- este ultimo passa a ser consequencia
-- de uma aprovacao, nunca um valor escolhido livremente pelo tutor.
-- =====================================================================

CREATE TABLE vet_link_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id          BIGINT      NOT NULL,
    veterinarian_id BIGINT      NOT NULL,
    requested_by_id BIGINT      NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    message         VARCHAR(300),
    response_note   VARCHAR(300),
    created_at      TIMESTAMP   NOT NULL,
    responded_at    TIMESTAMP,

    CONSTRAINT fk_vet_link_pet FOREIGN KEY (pet_id)
        REFERENCES pets (id) ON DELETE CASCADE,
    CONSTRAINT fk_vet_link_veterinarian FOREIGN KEY (veterinarian_id)
        REFERENCES veterinarians (id) ON DELETE CASCADE,
    CONSTRAINT fk_vet_link_requested_by FOREIGN KEY (requested_by_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- Indice unico parcial: impede duas solicitacoes PENDENTES para o mesmo par
-- (pet, veterinario), mas permite historico de solicitacoes ja respondidas.
-- E o complemento no banco da validacao feita no VetLinkRequestService.
CREATE UNIQUE INDEX uk_vet_link_pending
    ON vet_link_requests (pet_id, veterinarian_id)
    WHERE status = 'PENDING';

CREATE INDEX idx_vet_link_vet_status ON vet_link_requests (veterinarian_id, status);
CREATE INDEX idx_vet_link_pet        ON vet_link_requests (pet_id);
